#!/usr/bin/env bash
# HiTechCloud hitechcloud-tools-sdk SDK
SCRIPT_DIR="${BASH_SOURCE[0]%/*}"
source "${SCRIPT_DIR}/lib/chuyen_doi_and_dinh_dang.sh"
source "${SCRIPT_DIR}/lib/cong_cu_lap_trinh.sh"
source "${SCRIPT_DIR}/lib/doanh_nghiep_and_thue.sh"
source "${SCRIPT_DIR}/lib/du_lieu_viet_nam.sh"
source "${SCRIPT_DIR}/lib/duoc_pham_and_y_te.sh"
source "${SCRIPT_DIR}/lib/email_and_dns.sh"
source "${SCRIPT_DIR}/lib/ma_hoa_and_kiem_tra.sh"
source "${SCRIPT_DIR}/lib/mang_and_ha_tang.sh"
source "${SCRIPT_DIR}/lib/phap_ly_and_thu_tuc.sh"
source "${SCRIPT_DIR}/lib/qr_and_thanh_toan.sh"
source "${SCRIPT_DIR}/lib/seo_and_web.sh"
source "${SCRIPT_DIR}/lib/tai_chinh_and_ty_gia.sh"
source "${SCRIPT_DIR}/lib/ten_mien_and_ssl.sh"
source "${SCRIPT_DIR}/lib/thoi_gian_and_lich.sh"
source "${SCRIPT_DIR}/lib/xuat_nhap_khau_and_logistics.sh"
echo "HiTechCloud hitechcloud-tools-sdk SDK loaded."
